"""add casal ministerio

Revision ID: 00ea8bed83f1
Revises: 11b4b3f49804
Create Date: 2026-03-06 17:54:26.057489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ea8bed83f1'
down_revision = '11b4b3f49804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casal_ministerio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ministro_1', sa.Integer(), nullable=False),
    sa.Column('id_ministro_2', sa.Integer(), nullable=False),
    sa.Column('id_paroquia', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_ministro_1'], ['ministro.id'], ),
    sa.ForeignKeyConstraint(['id_ministro_2'], ['ministro.id'], ),
    sa.ForeignKeyConstraint(['id_paroquia'], ['paroquia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casal_ministerio')
    # ### end Alembic commands ###
