"""Atualização

Revision ID: 188272edd88d
Revises: 9ac9c459579b
Create Date: 2026-03-04 19:35:03.899476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188272edd88d'
down_revision = '9ac9c459579b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escala', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escala_id_ministro'), ['id_ministro'], unique=False)
        batch_op.create_index(batch_op.f('ix_escala_id_missa'), ['id_missa'], unique=False)

    with op.batch_alter_table('missa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_missa_data'), ['data'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_missa_data'))

    with op.batch_alter_table('escala', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escala_id_missa'))
        batch_op.drop_index(batch_op.f('ix_escala_id_ministro'))

    # ### end Alembic commands ###
