"""Escala inteligente

Revision ID: 3a7f2d1d1498
Revises: ed6934af330f
Create Date: 2026-03-10 18:08:07.158047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7f2d1d1498'
down_revision = 'ed6934af330f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presencas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ministro_id', sa.Integer(), nullable=False),
    sa.Column('missa_id', sa.Integer(), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ministro_id'], ['ministro.id'], ),
    sa.ForeignKeyConstraint(['missa_id'], ['missa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('missa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missa', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    op.drop_table('presencas')
    # ### end Alembic commands ###
