"""Adicionado login no Ministro

Revision ID: 41332449e31d
Revises: 8d1760c1704a
Create Date: 2026-03-03 08:48:05.218218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41332449e31d'
down_revision = '8d1760c1704a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    with op.batch_alter_table('ministro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_hash', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('pode_logar', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('primeiro_acesso', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ministro', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('primeiro_acesso')
        batch_op.drop_column('tipo')
        batch_op.drop_column('pode_logar')
        batch_op.drop_column('senha_hash')

    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('senha_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('id_paroquia', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_paroquia'], ['paroquia.id'], name=op.f('usuario_id_paroquia_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('usuario_pkey')),
    sa.UniqueConstraint('email', name=op.f('usuario_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
