"""Escala inteligente

Revision ID: 4fd5cda3a69c
Revises: c4d5e6f7a8b9
Create Date: 2026-03-12 17:31:50.693029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd5cda3a69c'
down_revision = 'c4d5e6f7a8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_substituicao', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pedido_substituicao_id_escala_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'escala', ['id_escala'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_substituicao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pedido_substituicao_id_escala_fkey'), 'escala', ['id_escala'], ['id'])

    # ### end Alembic commands ###
