"""mural ministros

Revision ID: 5cf421513d97
Revises: a0d98f28a007
Create Date: 2026-03-05 18:35:01.742698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf421513d97'
down_revision = 'a0d98f28a007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ministro', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ministro_email_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ministro', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('ministro_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
