"""Escala inteligente

Revision ID: 5dde2ae35a99
Revises: e6f7a8b9c0d1
Create Date: 2026-03-22 12:18:51.145967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dde2ae35a99'
down_revision = 'e6f7a8b9c0d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extrato_importado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lancamento_financeiro_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_extrato_importado_lancamento_financeiro_id'), ['lancamento_financeiro_id'], unique=False)
        batch_op.create_foreign_key(None, 'lancamentos_financeiros', ['lancamento_financeiro_id'], ['id'])

    with op.batch_alter_table('extrato_padrao', schema=None) as batch_op:
        batch_op.alter_column('centro_custo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('lancamentos_financeiros', schema=None) as batch_op:
        batch_op.alter_column('centro_custo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos_financeiros', schema=None) as batch_op:
        batch_op.alter_column('centro_custo_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('extrato_padrao', schema=None) as batch_op:
        batch_op.alter_column('centro_custo_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('extrato_importado', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_extrato_importado_lancamento_financeiro_id'))
        batch_op.drop_column('lancamento_financeiro_id')

    # ### end Alembic commands ###
