"""add index to txid

Revision ID: 6dd4f8caa7af
Revises: dab29d7c4ec6
Create Date: 2026-04-16 14:18:00.533110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd4f8caa7af'
down_revision = 'dab29d7c4ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.alter_column('txid',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=25),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_pagamentos_external_id'))
        batch_op.create_index(batch_op.f('ix_pagamentos_external_id'), ['external_id'], unique=False)
        batch_op.create_index('idx_cliente_status', ['cliente_id', 'status'], unique=False)
        batch_op.create_index('idx_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('idx_txid_status', ['txid', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagamentos_txid'), ['txid'], unique=True)

    with op.batch_alter_table('rifas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rifas_numero'))
        batch_op.create_index(batch_op.f('ix_rifas_numero'), ['numero'], unique=False)
        batch_op.create_unique_constraint('uq_rifa_campanha_numero', ['campanha_id', 'numero'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rifas', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rifa_campanha_numero', type_='unique')
        batch_op.drop_index(batch_op.f('ix_rifas_numero'))
        batch_op.create_index(batch_op.f('ix_rifas_numero'), ['numero'], unique=True)

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamentos_txid'))
        batch_op.drop_index('idx_txid_status')
        batch_op.drop_index('idx_status_created')
        batch_op.drop_index('idx_cliente_status')
        batch_op.drop_index(batch_op.f('ix_pagamentos_external_id'))
        batch_op.create_index(batch_op.f('ix_pagamentos_external_id'), ['external_id'], unique=True)
        batch_op.alter_column('txid',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
