"""add vendedor to pagamentos

Revision ID: 751cd3ab567d
Revises: c6a1a1a911c1
Create Date: 2026-04-12 10:36:25.368859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751cd3ab567d'
down_revision = 'c6a1a1a911c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendedor', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_column('vendedor')

    # ### end Alembic commands ###
