"""fix migrations

Revision ID: 7dcb0d88643a
Revises: c8c7c841604c
Create Date: 2026-04-28 23:10:29.685012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dcb0d88643a'
down_revision = 'c8c7c841604c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=True))
        batch_op.alter_column('txid',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=35),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_pagamentos_cpf'), ['cpf'], unique=False)

    with op.batch_alter_table('vendedores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('vendedores_codigo_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_vendedores_codigo'))
        batch_op.create_index(batch_op.f('ix_vendedores_codigo'), ['codigo'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendedores_codigo'))
        batch_op.create_index(batch_op.f('ix_vendedores_codigo'), ['codigo'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('vendedores_codigo_key'), ['codigo'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamentos_cpf'))
        batch_op.alter_column('txid',
               existing_type=sa.String(length=35),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
