"""add txid to pagamento_rifa

Revision ID: 84228575856e
Revises: 751cd3ab567d
Create Date: 2026-04-16 09:42:40.786815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84228575856e'
down_revision = '751cd3ab567d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('txid', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_column('txid')

    # ### end Alembic commands ###
