"""add impresso controle

Revision ID: 89706e882cb2
Revises: 6dd4f8caa7af
Create Date: 2026-04-16 15:39:17.070024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89706e882cb2'
down_revision = '6dd4f8caa7af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impresso', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('impresso_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_column('impresso_em')
        batch_op.drop_column('impresso')

    # ### end Alembic commands ###
