"""Escala inteligente

Revision ID: 8a8598f6fc74
Revises: b7d2c4e8a1f0
Create Date: 2026-03-07 11:01:01.743665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8598f6fc74'
down_revision = 'b7d2c4e8a1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido_substituicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=120), nullable=False),
    sa.Column('id_escala', sa.Integer(), nullable=False),
    sa.Column('id_paroquia', sa.Integer(), nullable=False),
    sa.Column('id_ministro_solicitante', sa.Integer(), nullable=False),
    sa.Column('id_ministro_aceite', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('respondido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_escala'], ['escala.id'], ),
    sa.ForeignKeyConstraint(['id_ministro_aceite'], ['ministro.id'], ),
    sa.ForeignKeyConstraint(['id_ministro_solicitante'], ['ministro.id'], ),
    sa.ForeignKeyConstraint(['id_paroquia'], ['paroquia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedido_substituicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_substituicao_id_escala'), ['id_escala'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_substituicao_id_ministro_aceite'), ['id_ministro_aceite'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_substituicao_id_ministro_solicitante'), ['id_ministro_solicitante'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_substituicao_id_paroquia'), ['id_paroquia'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_substituicao_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_substituicao_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_substituicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_substituicao_token'))
        batch_op.drop_index(batch_op.f('ix_pedido_substituicao_status'))
        batch_op.drop_index(batch_op.f('ix_pedido_substituicao_id_paroquia'))
        batch_op.drop_index(batch_op.f('ix_pedido_substituicao_id_ministro_solicitante'))
        batch_op.drop_index(batch_op.f('ix_pedido_substituicao_id_ministro_aceite'))
        batch_op.drop_index(batch_op.f('ix_pedido_substituicao_id_escala'))

    op.drop_table('pedido_substituicao')
    # ### end Alembic commands ###
