"""estrutura inicial

Revision ID: 8d1760c1704a
Revises: 
Create Date: 2026-03-02 22:04:13.661116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1760c1704a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ministro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('comunidade', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ministro', schema=None) as batch_op:
        batch_op.drop_column('comunidade')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
