"""firebase tokens

Revision ID: 9ac9c459579b
Revises: 
Create Date: 2026-03-03 21:34:46.436054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac9c459579b'
down_revision = '0f1e2d3c4b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ministro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('notificacoes_ativas', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ministro', schema=None) as batch_op:
        batch_op.drop_column('notificacoes_ativas')
        batch_op.drop_column('firebase_token')

    # ### end Alembic commands ###
