"""mural ministros

Revision ID: a0d98f28a007
Revises: a9a90589fc6d
Create Date: 2026-03-05 18:06:53.747909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d98f28a007'
down_revision = 'a9a90589fc6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mural',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('imagem', sa.String(length=300), nullable=True),
    sa.Column('video', sa.String(length=300), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('id_ministro', sa.Integer(), nullable=True),
    sa.Column('id_paroquia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ministro'], ['ministro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mural_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('imagem', sa.String(length=300), nullable=True),
    sa.Column('video', sa.String(length=300), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('id_ministro', sa.Integer(), nullable=True),
    sa.Column('id_paroquia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ministro'], ['ministro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mural_comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('id_post', sa.Integer(), nullable=True),
    sa.Column('id_ministro', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_post'], ['mural_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mural_curtida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_post', sa.Integer(), nullable=True),
    sa.Column('id_ministro', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_post'], ['mural_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mural_curtida')
    op.drop_table('mural_comentario')
    op.drop_table('mural_post')
    op.drop_table('mural')
    # ### end Alembic commands ###
