"""Escala inteligente

Revision ID: a89a8b8154fd
Revises: 8a8598f6fc74
Create Date: 2026-03-09 10:56:18.120025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89a8b8154fd'
down_revision = '8a8598f6fc74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ministro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_completo', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ministro', schema=None) as batch_op:
        batch_op.drop_column('nome_completo')

    # ### end Alembic commands ###
