"""avisos

Revision ID: a9a90589fc6d
Revises: 188272edd88d
Create Date: 2026-03-05 16:53:20.531735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a90589fc6d'
down_revision = '188272edd88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('arquivo', sa.String(length=300), nullable=True),
    sa.Column('video_url', sa.String(length=300), nullable=True),
    sa.Column('fixado', sa.Boolean(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avisos')
    # ### end Alembic commands ###
