"""indisponibilidade fixa

Revision ID: aa532a8e28c2
Revises: 5cf421513d97
Create Date: 2026-03-06 08:16:40.149784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa532a8e28c2'
down_revision = '5cf421513d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indisponibilidade_fixa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ministro', sa.Integer(), nullable=False),
    sa.Column('id_paroquia', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Integer(), nullable=True),
    sa.Column('dia_semana', sa.Integer(), nullable=True),
    sa.Column('horario', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['id_ministro'], ['ministro.id'], ),
    sa.ForeignKeyConstraint(['id_paroquia'], ['paroquia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indisponibilidade_fixa')
    # ### end Alembic commands ###
