"""mensagem

Revision ID: c6a1a1a911c1
Revises: c4f5a6b7d8e9
Create Date: 2026-04-11 14:45:06.065301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a1a1a911c1'
down_revision = 'c4f5a6b7d8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.String(length=255), nullable=True))

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pagamentos_external_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_pagamentos_external_id'))
        batch_op.create_index(batch_op.f('ix_pagamentos_external_id'), ['external_id'], unique=True)

    with op.batch_alter_table('rifas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('rifas_numero_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_rifas_numero'))
        batch_op.create_index(batch_op.f('ix_rifas_numero'), ['numero'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rifas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rifas_numero'))
        batch_op.create_index(batch_op.f('ix_rifas_numero'), ['numero'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('rifas_numero_key'), ['numero'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamentos_external_id'))
        batch_op.create_index(batch_op.f('ix_pagamentos_external_id'), ['external_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('pagamentos_external_id_key'), ['external_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###
