"""Escala inteligente

Revision ID: d6634527d3df
Revises: 3a7f2d1d1498
Create Date: 2026-03-10 18:26:37.717752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6634527d3df'
down_revision = '3a7f2d1d1498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presencas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_missa', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('presencas_missa_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'missa', ['id_missa'], ['id'])
        batch_op.drop_column('missa_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presencas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('missa_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('presencas_missa_id_fkey'), 'missa', ['missa_id'], ['id'])
        batch_op.drop_column('id_missa')

    # ### end Alembic commands ###
