"""add origem to pagamento_rifa

Revision ID: dab29d7c4ec6
Revises: 84228575856e
Create Date: 2026-04-16 11:31:42.691394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab29d7c4ec6'
down_revision = '84228575856e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origem_pagamento', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_column('origem_pagamento')

    # ### end Alembic commands ###
