"""Escala inteligente

Revision ID: ed6934af330f
Revises: a89a8b8154fd
Create Date: 2026-03-10 15:01:26.773774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed6934af330f'
down_revision = 'a89a8b8154fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escala', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_escala_ministro'))
        batch_op.drop_index(batch_op.f('idx_escala_missa'))

    with op.batch_alter_table('ministro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ministro_paroquia'))

    with op.batch_alter_table('missa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_missa_data'))

    with op.batch_alter_table('paroquia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paroquia', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('ativo')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')

    with op.batch_alter_table('missa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_missa_data'), ['data'], unique=False)

    with op.batch_alter_table('ministro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ministro_paroquia'), ['id_paroquia'], unique=False)

    with op.batch_alter_table('escala', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_escala_missa'), ['id_missa'], unique=False)
        batch_op.create_index(batch_op.f('idx_escala_ministro'), ['id_ministro'], unique=False)

    # ### end Alembic commands ###
